name: CI/CD Workflow for driver-did-factom

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build and test
        run: mvn -B clean install -Dmaven.test.skip=true --file pom.xml
      - name: Docker Build and Push
        uses: danubetech/github-action-docker-build-push@master
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_FILE: Dockerfile
          CONTAINER_TAG: sphereon/uni-resolver-driver-did-factom:latest
